Code & Features Update

diff --git a/pixtrm b/pixtrm
--- a/pixtrm
+++ b/pixtrm
@@ -2,51 +2,90 @@
 
 # dependencies /////////////////////////////////////////////////////////////////
 
-if [ -f "${HOME}"/.local/bin/frobulator ]
+ticker () {
+
+	echo
+
+	for ticker in '>  ' '>> ' '>>>'
+	do
+		echo -n -e "\r[  ${ticker}  ] ${1^}..."
+
+		sleep 0.5
+	done
+
+	echo
+
+	echo
+
+}
+
+if [[ $(id -u -n) = "root" ]]
 then
-	rm -r -f "${HOME}"/.local/bin/frobulator
+	USER="${SUDO_USER:-root}"
+
+	if [ "${USER}" = "root" ]
+	then
+		HOME=/root
+	else
+		HOME="/home/${USER}"
+	fi
 fi
 
-if [[ -z $(command -v frobulator) ]]
+ticker checking
+
+package_managers_list=(
+	"apt-get --quiet --quiet update > /dev/null 2>&1; apt-get --quiet --quiet install --yes"
+	"dnf --quiet install --assumeyes"
+	"yum --quiet install --assumeyes"
+	"apk add --quiet"
+	"pacman --sync --refresh --noconfirm --noprogressbar"
+	"zypper --quiet --non-interactive install"
+)
+
+package="curl"
+
+if [[ -z $(command -v "${package}") ]]
 then
-	if [[ $(id -u -n) = "root" ]]
+	for package_manager in "${package_managers_list[@]}"
+	do
+		entry="${package_manager%% *}"
+
+		if [[ -n $(command -v "${entry}") ]]
+		then
+			eval "${package_manager} ${package} > /dev/null 2>&1"
+
+			break
+		fi
+	done
+
+	if [[ -z $(command -v "${package}") ]]
 	then
-		SUDO_HOME=/root
+		echo "[  !  ] Unable to install or binary not found /////////////////////// [ '${package}' ]"
+		echo
 
-		USER="${SUDO_USER}"
-
-		HOME=/home/"${USER}"
+		exit 1
 	fi
-
-	if [[ -z $(command -v curl) ]]
-	then
-		yes | apt-get install curl
-	fi
-
-	if [ ! -d "${HOME}"/.local/bin ]
-	then
-		mkdir -p "${HOME}"/.local/bin
-	fi
-
-	if [[ $(id -u -n) = "root" ]]
-	then
-		chown "${USER}":"${USER}" "${HOME}"/.local/*
-
-		chmod -R 777 "${HOME}"/.local/*
-	fi
-
-	curl -s -L get.frbltr.app > "${HOME}"/.local/bin/frobulator
-
-	chmod +x "${HOME}"/.local/bin/frobulator
 fi
 
-. "${HOME}"/.local/bin/frobulator
+mkdir -p "${HOME}"/.local/bin
 
-# superuser ////////////////////////////////////////////////////////////////////
+frobulator="${HOME}"/.local/bin/frobulator
 
-export self_arguments="${@}"
+version_online=$(curl -s -L get.frbltr.app | grep -m 1 '^# version=' | cut -d '"' -f 2)
+version_local=$(grep -m 1 '^# version=' "${frobulator}" 2>/dev/null | cut -d '"' -f 2)
 
-# frobulator.escalate
+version_local="${version_local:-1970-01-01}"
+
+if [ ! -f "${frobulator}" ] || [[ "${version_online}" > "${version_local}" ]]
+then
+	curl -s -L get.frbltr.app > "${frobulator}"
+
+	chmod +x "${frobulator}"
+fi
+
+ticker initializing
+
+source "${frobulator}"
 
 # script ///////////////////////////////////////////////////////////////////////
 
